### ISSUE TITLE
Allow Surplus Donations

### ISSUE THREAD

**Issue by kirstin** [roschaefer/rundfunk-mitbestimmen#16]
The Rundfunkbeitrag is the minimal amount users have to distribute to shows or projects they like.

However if people like to, they should be allowed to donate more of their money than their Rundfunkbeitrag to Projects.

I propose:
Allow extra donations by users. 

For this to work properly and efficiently I believe it is a good idea to have the feature of making what each show/project needs transparent, as mentioned in #15 .

Taking 1-5% of this money could be a business model. The relative amount donated could also be variable and chosen by the user.

**Comment by roschaefer** [comment]
I like your idea that people can opt-in to donate more money. That would give the Beitragsservice the character of a micro-donation service. I like that because it fits very well with my vision that any kind of content on the web could receive donations from the Rundfunkbeitrag, not only public broadcasting.

However I'm concerned about your second idea. I would be afraid that monetizing this app could lead to a loss of confidence. Just think that we are kindly asking citizen to provide us with their personal data - voluntarily. That's why I see the backing of this app in a non-profit organization rather than in a startup.

**Comment by roschaefer** [comment]
See #15
