### ISSUE TITLE
Find-broadcast: Sort has no effect in a search

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#301]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
If your search returns many results and you click on the sort buttons, the order stays the same.

* **What is the expected behavior?**
The search results should be ordered ascending/descending by name.

* **What is the motivation / use case for changing the behavior?**
You want to override the order by relevance with a custom ordering.

* **If the current behavior is a bug, please tell us:**
  * Steps to reproduce
1. Visit `/find-broadcasts`
2. Search for "Krimi"
3. Click on the A->Z button on the top right
4. Broadcasts are ordered as before

  * The version of your browser, local postgresql installation and operating system
Chromum 61, Postgres 9.6.5, Archlinux 4.12.12-1-ARCH
  * A screenshot

![selection_044](https://user-images.githubusercontent.com/2110676/31301056-96820b0a-aaf7-11e7-97de-5e9ce0bd103b.png)

  * Stacktraces, related issues, suggestions how to fix
Let the last call to `order` in `app/controller/broadcasts_controller` win over the order of the `full_search`.

**Comment by domangi** [comment]
The problem is that pg_search uses his ranking for result ordering, and when you chain another ordering, in this case the title, this is appended to the pg_search_rank ordering:

`@broadcasts = Broadcast.full_search("d")`

`  Broadcast Load (4.8ms)  SELECT "broadcasts".* FROM "broadcasts" INNER JOIN (SELECT "broadcasts"."id" AS pg_search_id, (ts_rank((setweight(to_tsvector('simple', coalesce("broadcasts"."title"::text, '')), 'A') || setweight(to_tsvector('simple', coalesce("broadcasts"."description"::text, '')), 'C') ...... ORDER BY pg_search_e8b13f8eebf238007d1aa3.rank DESC, "broadcasts"."id" ASC`

`@broadcasts.order(:title)`
` Broadcast Load (6.3ms)  SELECT "broadcasts".* FROM "broadcasts" INNER JOIN (SELECT "broadcasts"."id" AS pg_search_id, (ts_rank((setweight(to_tsvector('simple', coalesce("broadcasts"."title"::text, '')), 'A') || setweight(to_tsvector('simple', coalesce("broadcasts"."description"::text, '')), 'C') || setweight(to_tsvector('simple', coalesce(pg_search_2acda8b9049bb58df7d4fa.pg_search_778d1625f397087f0ef6cc::text, '')), 'B')), (to_tsquery('simple', ''' ' || 'd' || ' ''')), 0)) ...... ORDER BY pg_search_e8b13f8eebf238007d1aa3.rank DESC, "broadcasts"."id" ASC, "broadcasts"."title" ASC
`

This way the title ordering has only effect if the pg_search_rank is equal.

The problem can be solved using [reorder](http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-reorder) instead of order, so that the existing ording is replaced.

I will try to setup a test scenario for the current error and then fix it.
