### ISSUE TITLE
Invoice: Rounding error?

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/rundfunk-mitbestimmen#32]
Sometimes an amount does not get saved exactly as I enter it, e.g. `5.0€` turns into `4.99€` even though there is still enough available money.

**Comment by domangi** [comment]
This is caused by how numbers are stored in memory by javascript. When you click enter a function called "allocate" in invoice.js is used to check if the new amount can be allocated all or only part of it (I think) and to do so it calculates the difference between the old value and the new value:

https://github.com/roschaefer/rundfunk-mitbestimmen/blob/master/frontend/app/models/invoice.js#L72
`let diff = Math.min(poolBudget, this.floor10(desiredAmount - currentAmount, -2));`

 In particular, "desiredAmount - currentAmount" will return a value that is not exact, e.g. 5.00-5.01 =
-0.009999999999999787

To fix it I would round the result of the difference to 2 decimals:

`let diff = Math.min(poolBudget, this.floor10((desiredAmount - currentAmount).toFixed(2), -2));`

**Comment by roschaefer** [comment]
@domangi if you write `close [issue_number]` in the description of the pull request at the top, the issue will be auto-closed: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by roschaefer** [comment]
closed via #286
