### ISSUE TITLE
Statistic: Display `null` values properly and order `null` to be less than zero

### ISSUE THREAD

**Issue by davidak** [roschaefer/rundfunk-mitbestimmen#431]
* **I'm submitting a ...**
  * bug report

* **What is the current behavior?**
When i sort after "on everage", the highest amount is 0€, later on page 3 comes 9,94€...

* **What is the expected behavior?**
9 should be higher than 0 ;)

* **What is the motivation / use case for changing the behavior?**
mathematically correctness

* **If the current behavior is a bug, please tell us (otherwise delete):**
  * Steps to reproduce
1. open https://rundfunk-mitbestimmen.de/statistics?column=average&page=3
2. see the results

  * The version of your browser, local postgresql installation and operating system
Chromium 62, no postgres O_o, elementary OS Loki (based on Ubuntu 16.04 LTS)
  * A screenshot
![screenshot from 2017-11-27 14 53 15](https://user-images.githubusercontent.com/91113/33270140-4ce1cf62-d383-11e7-9cd4-04377355385b.png)

  * Stacktraces, related issues, suggestions how to fix
sadly no

* **What could be a possible solution? (not obligatory)**
analyze and fix the bug :)

**Comment by roschaefer** [comment]
I can confirm. Ember inspector tells me it's because of `null` vavlues.
![selection_104](https://user-images.githubusercontent.com/2110676/33270506-969ec49c-d384-11e7-968e-5ac0e55880c9.png)

While `null` is technically correct, it should display `-` instead of `0.00€` and the backend should order `nil < 0.00`.
